---

# Main collection of env. vars to set for all tasks and scripts.
env:
    # Shell used to execute all script commands
    CIRRUS_SHELL: "/bin/bash"
    # No need to go crazy, but grab enough to cover most PRs
    CIRRUS_CLONE_DEPTH: 10
    # Prefix git URL for every container tool's repo home
    REPO_PREFIX: https://github.com/containers

gcp_credentials: ENCRYPTED[88b219cf6b4f2d70c4ff7f8c6c3186396102e14a27b47b985e40a0a0bc5337a270f9eee195b36ff6b3e2f07558998a95]

validate_task:
    name: "Validate"
    alias: "validate"
    only_if: &is_pr $CIRRUS_PR != ''
    timeout_in: 5m
    container: &ci_container
        # Ref: https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment
        dockerfile: "ci/Containerfile"
        cpu: 1
        memory: 1
    script:
        - "ci/shellcheck.sh"
        - "ci/validate.sh"

test_build-push_task:
    name: "Test build-push scripts function"
    alias: test_build-push
    only_if: *is_pr
    # No need to test if changes don't include ...
    skip: "!changesInclude('.cirrus.yml', 'build-push/**/*')"
    depends_on:
        - validate
    gce_instance: &build_push_test_vm
        image_project: "libpod-218412"
        image_family: 'build-push-cache'
        zone: "us-central1-a"
        disk: 200
    script: |
      bash ./build-push/.install.sh
      bash ./build-push/test.sh

test_image_build_task:
    alias: test_image_build
    name: Test build ${REPO_NAME}/${FLAVOR_NAME} image
    only_if: *is_pr
    depends_on:
        - test_build-push
    gce_instance: &build_push
        <<: *build_push_test_vm
        type: "t2d-standard-4"  # Extra muscle needed for multi-arch emulation
    env:
        ARCHES: amd64
        DRYRUN: 1  # Don't actually push anything, only build.
        A_DEBUG: 1
    matrix: &pbs_matrix
        - env:
              FLAVOR_NAME: upstream
          matrix: &pbs_images
                - env:
                      REPO_NAME: podman
                      CTX_SUB: podman/$FLAVOR_NAME
                      skip: "!changesInclude('.cirrus.yml', 'build-push/**/*', 'podman/**/*')"
                - env:
                      REPO_NAME: buildah
                      CTX_SUB: buildah
                      skip: "!changesInclude('.cirrus.yml', 'build-push/**/*', 'buildah/**/*')"
                - env:
                      REPO_NAME: skopeo
                      CTX_SUB: skopeo/$FLAVOR_NAME
                      skip: "!changesInclude('.cirrus.yml', 'build-push/**/*', 'skopeo/**/*')"
        - env:
              FLAVOR_NAME: testing
          matrix: *pbs_images
        - env:
              FLAVOR_NAME: stable
          matrix: *pbs_images
    script: &pbs_script |
        bash ./build-push/.install.sh
        source /etc/automation_environment
        # The '.' prefix to repo URL is significant - it means do not clone.
        containers_build_push.sh .${REPO_PREFIX}/${REPO_NAME}.git $CTX_SUB $FLAVOR_NAME

cron_image_build_task:
    alias: cron_image_build
    name: Build ${REPO_NAME}/${FLAVOR_NAME} image
    only_if: $CIRRUS_CRON == 'cron_image_build_task'
    gce_instance: *build_push
    env:
        CONTAINERS_USERNAME: ENCRYPTED[f94aa9610f678dc79ca45d49ee4c41a43da9468094883eb386ea907f6218cd49df61f892105109da8b5309523db3ed0b]
        CONTAINERS_PASSWORD: ENCRYPTED[84a2784130e2c359afa70ad0575b04f448d248ca947d130d3450eb01676e7f934b6de621a167edf56cd4901396dfe7e2]
        PODMAN_USERNAME: ENCRYPTED[c7c6506427eeecce7c709a94fb7547987545cb4ba7e607e249444b3588a41069ad116781f3187018c12c6fff0fd425d7]
        PODMAN_PASSWORD: ENCRYPTED[f7c321e7dfb017e4111e0fc3c0f7eb2e743d11f4eddca5cf209c2f25e2c778eb33ab746b6ef91233e570ac3d547a86f0]
        BUILDAH_USERNAME: ENCRYPTED[58742c385f0938a25cd523837bee50bf40db7c2523dc4506b9a1c3d72233e828ad9527ca638c18eb825d2ceef6d5b31d]
        BUILDAH_PASSWORD: ENCRYPTED[3d400b0547ef4d56c54dbf05e2ecdc0a1d5b2a3013f194b3e090bed6b1ab67fafbef6dca06cbb2b889b88f894143d40a]
        SKOPEO_USERNAME: ENCRYPTED[7290f519ec778c3f21353c0279f55ff6e2a59d9fd9b816db8f0a0549f2ea22efc297feb9f7422a6b9f2a6c22f30e1027]
        SKOPEO_PASSWORD: ENCRYPTED[ad43d3aefef388b22c2e0c837678ff3754994563dbe9574717e7aa68a847e64401b501c882d733149d7896a1d617f806]
    matrix: *pbs_matrix
    script: *pbs_script

success_task:
    alias: success
    name: Total Success
    only_if: *is_pr
    depends_on:
        - validate
        - test_build-push
        - test_image_build
    container:
        <<: *ci_container
    clone_script: /bin/true
    script: /bin/true
